package src.terrain;

import src.model.Vertex;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.*;

import org.tinfour.standard.IncrementalTin;
import org.tinfour.common.SimpleTriangle;
import org.tinfour.utils.TriangleCollector;

/**
 * Generates a triangular mesh from a ground-filtered point cloud and
 * writes it as a PLY file readable by {@link src.io.PLYParser}.
 *
 * <h3>Algorithm</h3>
 * <p>Triangulates in the XY plane (correct for terrain — elevation is Z,
 * not a true 3D surface) using Tinfour's {@link IncrementalTin}, a
 * production-grade incremental Delaunay triangulator built for large
 * LiDAR/terrain point sets. This replaces a hand-rolled spatially-indexed
 * Bowyer-Watson implementation that degraded badly on real survey data —
 * triangles touching the initial super-triangle's corners could have
 * circumcircles spanning a large fraction of the point cloud's bounding
 * box, making the spatial index's add/remove cost effectively O(n) per
 * insertion in the worst case. Tinfour benchmarks in excess of one
 * million points per second on typical hardware.</p>
 *
 * <h3>Usage</h3>
 * <pre>
 *   MeshGenerator.generate(groundPoints, "data/meshes/terrain.ply");
 * </pre>
 */
public class MeshGenerator {

    private MeshGenerator() {}

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    public static void generate(List<Vertex> points, String filePath) throws IOException {
        if (points.size() < 3) {
            throw new IllegalArgumentException(
                "At least 3 points are required (got " + points.size() + ").");
        }

        System.out.printf("MeshGenerator: triangulating %d points...%n", points.size());
        long t0 = System.currentTimeMillis();

        List<Triangle> triangles = delaunay(points);

        long ms = System.currentTimeMillis() - t0;
        System.out.printf("MeshGenerator: %d triangles in %d ms%n", triangles.size(), ms);

        writePLY(points, triangles, filePath);
        System.out.printf("MeshGenerator: mesh written to %s%n", filePath);
    }

    // -------------------------------------------------------------------------
    // Delaunay triangulation (Tinfour)
    // -------------------------------------------------------------------------

    private static List<Triangle> delaunay(List<Vertex> points) {
        IncrementalTin tin = new IncrementalTin();

        // Map each app-level Vertex id back to the original object, so we
        // can recover it (with its z-value, etc.) from the triangles
        // Tinfour hands back.
        Map<Integer, Vertex> byId = new HashMap<>(points.size() * 2);

        for (Vertex v : points) {
            byId.put(v.id, v);
            tin.add(new org.tinfour.common.Vertex(v.x, v.y, v.z, v.id));
        }

        List<Triangle> result = new ArrayList<>();
        TriangleCollector.visitSimpleTriangles(tin, (SimpleTriangle t) -> {
            Vertex a = byId.get(t.getVertexA().getIndex());
            Vertex b = byId.get(t.getVertexB().getIndex());
            Vertex c = byId.get(t.getVertexC().getIndex());
            if (a != null && b != null && c != null) {
                result.add(new Triangle(a, b, c));
            }
        });
        return result;
    }

    // -------------------------------------------------------------------------
    // PLY writer
    // -------------------------------------------------------------------------

    private static void writePLY(
            List<Vertex> points,
            List<Triangle> triangles,
            String filePath) throws IOException {

        try (PrintWriter out = new PrintWriter(new java.io.BufferedWriter(
                new java.io.FileWriter(filePath), 1 << 16))) {

            out.println("ply");
            out.println("format ascii 1.0");
            out.println("comment Generated by MeshGenerator (Tinfour Delaunay)");
            out.println("element vertex " + points.size());
            out.println("property float x");
            out.println("property float y");
            out.println("property float z");
            out.println("element face " + triangles.size());
            out.println("property list uchar int vertex_indices");
            out.println("end_header");

            Map<Integer, Integer> idToIndex = new HashMap<>(points.size() * 2);
            int idx = 0;
            for (Vertex v : points) {
                idToIndex.put(v.id, idx++);
                out.printf("%.6f %.6f %.6f%n", v.x, v.y, v.z);
            }

            for (Triangle t : triangles) {
                int ia = idToIndex.getOrDefault(t.a.id, -1);
                int ib = idToIndex.getOrDefault(t.b.id, -1);
                int ic = idToIndex.getOrDefault(t.c.id, -1);
                if (ia < 0 || ib < 0 || ic < 0) continue;
                out.printf("3 %d %d %d%n", ia, ib, ic);
            }
        }
    }

    // -------------------------------------------------------------------------
    // Geometry primitive
    // -------------------------------------------------------------------------

    /** A triangle referencing three of the app's own Vertex objects. */
    private static class Triangle {
        final Vertex a, b, c;
        Triangle(Vertex a, Vertex b, Vertex c) {
            this.a = a; this.b = b; this.c = c;
        }
    }

    // =========================================================================
    // Interactive entry point
    // =========================================================================

    /**
     * Interactive CLI entry point. Selects the best available point set
     * (subsampled > ground > raw), prompts for an output filename, runs
     * Delaunay triangulation, and stores the output path in
     * {@link SessionState#lastMeshPath}.
     */
    public static void run(java.util.Scanner sc, SessionState state) {
        final String MESH_DIR = "data/meshes/";
        new java.io.File(MESH_DIR).mkdirs();

        // Pick the best available source, with a clear explanation
        java.util.List<Vertex> source;
        String sourceLabel;
        if (state.subsampledPoints != null) {
            source = state.subsampledPoints;
            sourceLabel = "subsampled";
        } else if (state.groundPoints != null) {
            source = state.groundPoints;
            sourceLabel = "ground-filtered";
            System.out.println("  Note: using ground points directly (subsampling not run).");
            System.out.println("  Large clouds may be slow — consider subsampling first.");
        } else if (state.rawPoints != null) {
            source = state.rawPoints;
            sourceLabel = "raw";
            System.out.println("  Note: using raw points (CSF and subsampling not run).");
            System.out.println("  Ground filter is strongly recommended before meshing.");
        } else {
            System.out.println("  No point cloud loaded. Run 'Load point cloud' first.");
            return;
        }

        System.out.println("\n─────────────────────────────────────");
        System.out.println(" GENERATE MESH");
        System.out.println("─────────────────────────────────────");
        System.out.printf("  Source: %s points (%d pts)%n", sourceLabel, source.size());
        System.out.printf("  Output directory: %s%n", new java.io.File(MESH_DIR).getAbsolutePath());

        String def = "terrain_" + System.currentTimeMillis() + ".ply";
        System.out.printf("  Filename [default: %s]: ", def);
        String name = sc.nextLine().trim();
        if (name.isEmpty()) name = def;
        if (!name.toLowerCase().endsWith(".ply")) name += ".ply";

        String outPath = MESH_DIR + name;
        try {
            generate(source, outPath);
            state.lastMeshPath = outPath;
            System.out.printf("  Mesh saved to %s%n", new java.io.File(outPath).getAbsolutePath());
        } catch (java.io.IOException | IllegalArgumentException e) {
            System.out.printf("  Failed: %s%n", e.getMessage());
        }
    }
}